# Generated by Django 5.0 on 2023-12-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=255)),
                ('secret_access_key', models.CharField(max_length=255)),
                ('region_name', models.CharField(max_length=255)),
            ],
        ),
    ]
